#!/usr/bin/env python3
# Part 2: Add _build_ui method to MainWindow

with open('C:/Users/tmoph/OneDrive/Documents/Claude_code/sand_casting_v2/casting_sim.py', 'r') as f:
    content = f.read()

part2 = '''
    def _build_ui(self):
        main_layout = QHBoxLayout()
        main_widget = QWidget()
        main_widget.setLayout(main_layout)
        self.setCentralWidget(main_widget)

        splitter = QSplitter(Qt.Horizontal)
        main_layout.addWidget(splitter)

        left_panel = QVBoxLayout()
        left_widget = QWidget()
        left_widget.setLayout(left_panel)
        left_panel.setContentsMargins(10, 10, 10, 10)
        left_scroll = QScrollArea()
        left_scroll.setWidgetResizable(True)
        left_scroll.setWidget(left_widget)
        left_scroll.setMinimumWidth(320)
        splitter.addWidget(left_scroll)

        stl_group = QGroupBox("STL File")
        stl_layout = QVBoxLayout()
        self.load_btn = QPushButton("Load STL...")
        self.stl_label = QLabel("No file loaded")
        self.stl_label.setWordWrap(True)
        stl_layout.addWidget(self.load_btn)
        stl_layout.addWidget(self.stl_label)
        stl_group.setLayout(stl_layout)
        left_panel.addWidget(stl_group)

        parting_group = QGroupBox("Parting Line")
        parting_layout = QVBoxLayout()
        self.parting_slider = QSlider(Qt.Horizontal)
        self.parting_slider.setMinimum(5)
        self.parting_slider.setMaximum(95)
        self.parting_slider.setValue(50)
        self.cope_label = QLabel(COPE_COLOR)
        self.drag_label = QLabel(DRAG_COLOR)
        parting_layout.addWidget(QLabel("Position: 50%"))
        parting_layout.addWidget(self.parting_slider)
        parting_layout.addWidget(self.cope_label)
        parting_layout.addWidget(self.drag_label)
        parting_group.setLayout(parting_layout)
        left_panel.addWidget(parting_group)

        flask_group = QGroupBox("Flask Size")
        flask_layout = QVBoxLayout()
        self.flask_combo = QComboBox()
        self._flask_presets = {
            "6 x 6": (6, 6), "6 x 8": (6, 8), "8 x 10": (8, 10),
            "10 x 12": (10, 12), "12 x 14": (12, 14), "14 x 20": (14, 20),
        }
        for name in self._flask_presets:
            self.flask_combo.addItem(name)
        self.add_flask_btn = QPushButton("+ Custom")
        flask_layout.addWidget(self.flask_combo)
        flask_layout.addWidget(self.add_flask_btn)
        flask_group.setLayout(flask_layout)
        left_panel.addWidget(flask_group)

        gating_group = QGroupBox("Gating System")
        gating_layout = QVBoxLayout()
        self.gating_checkboxes = {}
        for comp in ["Tapered Sprue", "Runner (Horizontal)", "Fan Gate",
                     "Side Gate", "Bottom Gate", "Riser (Open)"]:
            cb = QCheckBox(comp)
            self.gating_checkboxes[comp] = cb
            gating_layout.addWidget(cb)
        gating_group.setLayout(gating_layout)
        left_panel.addWidget(gating_group)

        metal_group = QGroupBox("Metal & Temperature")
        metal_layout = QVBoxLayout()
        self.metal_combo = QComboBox()
        for metal in METAL_DEFAULTS:
            self.metal_combo.addItem(metal)
        self.pour_spin = QSlider(Qt.Horizontal)
        self.pour_spin.setMinimum(1000)
        self.pour_spin.setMaximum(2500)
        self.pour_spin.setValue(660)
        self.mold_spin = QSlider(Qt.Horizontal)
        self.mold_spin.setMinimum(32)
        self.mold_spin.setMaximum(300)
        self.mold_spin.setValue(100)
        self.thin_combo = QComboBox()
        self.thin_combo.addItems(["No", "Yes"])
        metal_layout.addWidget(QLabel("Metal:"))
        metal_layout.addWidget(self.metal_combo)
        metal_layout.addWidget(QLabel("Pour Temp: 1300 F (default for A356)"))
        metal_layout.addWidget(self.pour_spin)
        metal_layout.addWidget(QLabel("Mold Temp: 100 F"))
        metal_layout.addWidget(self.mold_spin)
        metal_layout.addWidget(QLabel("Thin Wall?"))
        metal_layout.addWidget(self.thin_combo)
        metal_group.setLayout(metal_layout)
        left_panel.addWidget(metal_group)

        placement_group = QGroupBox("Model Placement")
        placement_layout = QVBoxLayout()
        self.x_slider = QSlider(Qt.Horizontal)
        self.x_slider.setMinimum(-500)
        self.x_slider.setMaximum(500)
        self.x_slider.setValue(0)
        self.y_slider = QSlider(Qt.Horizontal)
        self.y_slider.setMinimum(-500)
        self.y_slider.setMaximum(500)
        self.y_slider.setValue(0)
        self.z_slider = QSlider(Qt.Horizontal)
        self.z_slider.setMinimum(-200)
        self.z_slider.setMaximum(200)
        self.z_slider.setValue(0)
        self.rot_slider = QSlider(Qt.Horizontal)
        self.rot_slider.setMinimum(0)
        self.rot_slider.setMaximum(360)
        self.rot_slider.setValue(0)
        placement_layout.addWidget(QLabel("X Offset: 0 mm"))
        placement_layout.addWidget(self.x_slider)
        placement_layout.addWidget(QLabel("Y Offset: 0 mm"))
        placement_layout.addWidget(self.y_slider)
        placement_layout.addWidget(QLabel("Z Offset: 0 mm"))
        placement_layout.addWidget(self.z_slider)
        placement_layout.addWidget(QLabel("Rotation: 0 deg"))
        placement_layout.addWidget(self.rot_slider)
        placement_group.setLayout(placement_layout)
        left_panel.addWidget(placement_group)

        gating_placement_group = QGroupBox("Gating Placement")
        gating_placement_layout = QVBoxLayout()
        self.sprue_x_slider = QSlider(Qt.Horizontal)
        self.sprue_x_slider.setMinimum(-200)
        self.sprue_x_slider.setMaximum(200)
        self.sprue_x_slider.setValue(0)
        self.sprue_y_slider = QSlider(Qt.Horizontal)
        self.sprue_y_slider.setMinimum(-200)
        self.sprue_y_slider.setMaximum(200)
        self.sprue_y_slider.setValue(0)
        self.riser_x_slider = QSlider(Qt.Horizontal)
        self.riser_x_slider.setMinimum(-200)
        self.riser_x_slider.setMaximum(200)
        self.riser_x_slider.setValue(0)
        self.riser_y_slider = QSlider(Qt.Horizontal)
        self.riser_y_slider.setMinimum(-200)
        self.riser_y_slider.setMaximum(200)
        self.riser_y_slider.setValue(0)
        gating_placement_layout.addWidget(QLabel("Sprue X: 0 mm"))
        gating_placement_layout.addWidget(self.sprue_x_slider)
        gating_placement_layout.addWidget(QLabel("Sprue Y: 0 mm"))
        gating_placement_layout.addWidget(self.sprue_y_slider)
        gating_placement_layout.addWidget(QLabel("Riser X: 0 mm"))
        gating_placement_layout.addWidget(self.riser_x_slider)
        gating_placement_layout.addWidget(QLabel("Riser Y: 0 mm"))
        gating_placement_layout.addWidget(self.riser_y_slider)
        gating_placement_group.setLayout(gating_placement_layout)
        left_panel.addWidget(gating_placement_group)

        shrink_group = QGroupBox("Shrinkage Compensation")
        shrink_layout = QVBoxLayout()
        self.shrink_slider = QSlider(Qt.Horizontal)
        self.shrink_slider.setMinimum(100)
        self.shrink_slider.setMaximum(110)
        self.shrink_slider.setValue(106)
        shrink_pct = METAL_DEFAULTS["A356 Aluminum"]["shrinkage_pct"]
        self.shrink_label = QLabel("Shrinkage: " + str(shrink_pct) + "% (A356 Aluminum)")
        shrink_layout.addWidget(self.shrink_label)
        shrink_layout.addWidget(self.shrink_slider)
        shrink_group.setLayout(shrink_layout)
        left_panel.addWidget(shrink_group)

        self.progress_bar = QProgressBar()
        self.progress_bar.setVisible(False)
        left_panel.addWidget(self.progress_bar)

        center_panel = QVBoxLayout()
        center_widget = QWidget()
        center_widget.setLayout(center_panel)
        center_panel.setContentsMargins(10, 10, 10, 10)
        view_label = QLabel("3D Part Viewer")
        view_label.setAlignment(Qt.AlignCenter)
        center_panel.addWidget(view_label)
        self.render_frame = self.viewport
        if hasattr(self.viewport, "render_frame"):
            center_panel.addWidget(self.viewport.render_frame)
        else:
            center_panel.addWidget(self.viewport)
        view_btn_layout = QVBoxLayout()
        for view in ["Top", "Bottom", "Front", "Back", "Left", "Right", "Isometric"]:
            btn = QPushButton(view)
            btn.clicked.connect(lambda _, v=view: self.viewport.set_view(v))
            view_btn_layout.addWidget(btn)
        center_panel.addLayout(view_btn_layout)
        splitter.addWidget(center_widget)

        right_panel = QVBoxLayout()
        right_widget = QWidget()
        right_widget.setLayout(right_panel)
        right_panel.setContentsMargins(10, 10, 10, 10)
        result_label = QLabel("Simulation Results")
        result_label.setAlignment(Qt.AlignCenter)
        right_panel.addWidget(result_label)
        self.results_text = QTextEdit()
        self.results_text.setReadOnly(True)
        self.results_text.setMinimumWidth(350)
        right_panel.addWidget(self.results_text)
        self.sim_btn = QPushButton("Simulate Pour")
        self.sim_btn.setStyleSheet("QPushButton { background-color: #89B4FA; color: black; padding: 10px; font-weight: bold; }")
        self.reset_btn = QPushButton("Reset")
        self.reset_btn.setStyleSheet("QPushButton { background-color: #F38BA8; color: black; padding: 10px; }")
        btn_layout = QHBoxLayout()
        btn_layout.addWidget(self.sim_btn)
        btn_layout.addWidget(self.reset_btn)
        right_panel.addLayout(btn_layout)
        splitter.addWidget(right_widget)

'''

with open('C:/Users/tmoph/OneDrive/Documents/Claude_code/sand_casting_v2/casting_sim.py', 'a') as f:
    f.write(part2)

print("Part 2 written")
